import { type ModuleManifest } from '../types';
import {
  NetWorthWidget,
  AccountsOverviewWidget,
  RecentTransactionsWidget,
  IncomeVsExpensesWidget,
  SpendingByCategoryWidget,
  CashFlowWidget,
  StreakWidget,
  HealthScoreWidget,
} from '@/components/dashboard/widgets';

export const coreManifest: ModuleManifest = {
  id: 'core',
  name: 'Core',
  description: 'Essential transaction tracking and account management',
  icon: '💰',

  routes: [
    {
      path: '/dashboard',
      label: 'Dashboard',
      icon: 'LayoutDashboard',
      order: 0,
    },
    {
      path: '/transactions',
      label: 'Transactions',
      icon: 'Receipt',
      order: 1,
    },
    {
      path: '/accounts',
      label: 'Accounts',
      icon: 'Wallet',
      order: 2,
    },
    {
      path: '/categories',
      label: 'Categories',
      icon: 'Tags',
      order: 3,
    },
  ],

  dashboardWidgets: [
    {
      id: 'net-worth',
      name: 'Net Worth',
      description: 'Total balance across all accounts',
      sizes: ['S', 'M'],
      defaultSize: 'S',
      component: NetWorthWidget,
    },
    {
      id: 'accounts-overview',
      name: 'Accounts Overview',
      description: 'List of accounts with balances',
      sizes: ['M', 'L'],
      defaultSize: 'M',
      component: AccountsOverviewWidget,
    },
    {
      id: 'recent-transactions',
      name: 'Recent Transactions',
      description: 'Last 5-10 transactions',
      sizes: ['M', 'L'],
      defaultSize: 'M',
      component: RecentTransactionsWidget,
    },
    {
      id: 'income-vs-expenses',
      name: 'Income vs Expenses',
      description: 'Bar chart comparing income and expenses by month',
      sizes: ['M', 'L'],
      defaultSize: 'M',
      component: IncomeVsExpensesWidget,
    },
    {
      id: 'spending-by-category',
      name: 'Spending by Category',
      description: 'Pie chart of spending breakdown',
      sizes: ['S', 'M', 'L'],
      defaultSize: 'M',
      component: SpendingByCategoryWidget,
    },
    {
      id: 'cash-flow',
      name: 'Cash Flow',
      description: 'Income minus expenses for current period',
      sizes: ['S', 'M'],
      defaultSize: 'M',
      component: CashFlowWidget,
    },
    {
      id: 'streak',
      name: 'Logging Streak',
      description: 'Track your consecutive days of logging transactions',
      sizes: ['S', 'M', 'L'],
      defaultSize: 'S',
      component: StreakWidget,
    },
    {
      id: 'health-score',
      name: 'Financial Health',
      description: 'Your overall financial health score',
      sizes: ['S', 'M', 'L'],
      defaultSize: 'M',
      component: HealthScoreWidget,
    },
  ],
  formExtensions: [],
  settings: [],
  nudges: [],
};
